[package]
name = "apng"
version = "0.1.0"
authors = ["poccariswet <s1240231@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.0"
failure = "*"
byteorder = "1.3.2"
flate2 = "1.0.11"
